const ENABLE_STATUS = 0;
const DISABLE_STATUS = 1;
const CUSTOMER_TYPE = 0;
const SUPPLIER_TYPE = 1;
const BOTH_TYPE = 2;
export { ENABLE_STATUS, DISABLE_STATUS, CUSTOMER_TYPE, SUPPLIER_TYPE, BOTH_TYPE };
